"""
Autoencoder pretraining for PPO visual encoder weights.

Trains a CNN autoencoder whose encoder exactly matches the PPO agent's
visual_encoder on a pre-generated dataset of focal-plane images.

Dataset: generated by generate_autoencoder_dataset.py, stored as .npz
files in a folder (default: datasets/autoencoder/).

Usage:
    python train/ppo/train_ppo_autoencoder.py                           # full run
    python train/ppo/train_ppo_autoencoder.py --fast                    # smoke test
    python train/ppo/train_ppo_autoencoder.py --dataset-dir datasets/autoencoder
    python train/ppo/train_ppo_autoencoder.py --channel-scale 32 --fc-scale 256
"""

import os
import sys
import glob
import time
import argparse
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from pathlib import Path
from torch.utils.tensorboard import SummaryWriter
from torch.utils.data import TensorDataset, DataLoader

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from models.td3_models import conv_init, layer_init

_DEFAULT_DATASET_DIR = os.path.join(_REPO_ROOT, "datasets", "autoencoder")


# ============================================================================
# Autoencoder model
# ============================================================================

class OptomechAutoencoder(nn.Module):
    """CNN autoencoder whose encoder matches the PPO visual_encoder exactly.

    Architecture:
        encoder: Conv(in,cs,8,4) -> ReLU -> Conv(cs,2cs,4,2) -> ReLU -> Conv(2cs,4cs,2,2) -> ReLU
        bottleneck_encode: Flatten -> Linear(flat, fc_scale) -> ReLU
        bottleneck_decode: Linear(fc_scale, flat) -> ReLU -> Unflatten
        decoder: ConvT(4cs,2cs,2,2) -> ReLU -> ConvT(2cs,cs,4,2,op=1) -> ReLU -> ConvT(cs,in,8,4) -> Sigmoid
    """

    def __init__(self, obs_shape, channel_scale=32, fc_scale=256):
        super().__init__()
        self.obs_shape = obs_shape

        # Detect channels
        if obs_shape[-1] < obs_shape[0]:
            self.channels_last = True
            in_ch = obs_shape[-1]
        else:
            self.channels_last = False
            in_ch = obs_shape[0]

        cs = channel_scale
        self.in_ch = in_ch
        self.channel_scale = cs
        self.fc_scale = fc_scale

        # --- Encoder (exact PPO match) ---
        self.encoder = nn.Sequential(
            conv_init(nn.Conv2d(in_ch, cs, kernel_size=8, stride=4)),
            nn.ReLU(),
            conv_init(nn.Conv2d(cs, cs * 2, kernel_size=4, stride=2)),
            nn.ReLU(),
            conv_init(nn.Conv2d(cs * 2, cs * 4, kernel_size=2, stride=2)),
            nn.ReLU(),
        )

        # Compute encoder output shape
        with torch.inference_mode():
            dummy = torch.zeros(1, *obs_shape)
            if self.channels_last:
                dummy = dummy.permute(0, 3, 1, 2)
            enc_out = self.encoder(dummy)
            self.enc_shape = enc_out.shape[1:]  # (C, H, W)
            enc_flat = int(np.prod(self.enc_shape))

        # --- Bottleneck (matches PPO mlp) ---
        self.bottleneck_encode = nn.Sequential(
            nn.Flatten(),
            layer_init(nn.Linear(enc_flat, fc_scale)),
            nn.ReLU(),
        )
        self.bottleneck_decode = nn.Sequential(
            layer_init(nn.Linear(fc_scale, enc_flat)),
            nn.ReLU(),
        )

        # --- Decoder (mirror of encoder) ---
        self.decoder = nn.Sequential(
            conv_init(nn.ConvTranspose2d(cs * 4, cs * 2, kernel_size=2, stride=2)),
            nn.ReLU(),
            conv_init(nn.ConvTranspose2d(cs * 2, cs, kernel_size=4, stride=2, output_padding=1)),
            nn.ReLU(),
            nn.ConvTranspose2d(cs, in_ch, kernel_size=8, stride=4),
            nn.Sigmoid(),
        )

    def forward(self, x):
        if self.channels_last:
            x = x.permute(0, 3, 1, 2)
        z = self.encoder(x)
        b = self.bottleneck_encode(z)
        z_hat = self.bottleneck_decode(b).view(-1, *self.enc_shape)
        return self.decoder(z_hat)

    def encode(self, x):
        """Run encoder + bottleneck (matches PPO visual_encoder + mlp)."""
        if self.channels_last:
            x = x.permute(0, 3, 1, 2)
        return self.bottleneck_encode(self.encoder(x))


# ============================================================================
# Dataset loading
# ============================================================================

def load_dataset(dataset_dir, max_files=None):
    """Load all batch_*.npz files from the dataset directory.

    Two-pass approach to keep peak memory at ~1x dataset size:
      Pass 1: scan files for total count, shape, skip corrupted files.
      Pass 2: pre-allocate one tensor and fill it file-by-file.

    Returns (images_tensor, obs_ref_max).
    """
    pattern = os.path.join(dataset_dir, "batch_*.npz")
    files = sorted(glob.glob(pattern))
    if not files:
        raise FileNotFoundError(
            f"No batch_*.npz files found in {dataset_dir}. "
            f"Run generate_autoencoder_dataset.py first.")

    if max_files is not None:
        files = files[:max_files]

    total_files = len(files)
    t0 = time.time()

    # --- Pass 1: scan for total count and shape ---
    print(f"Scanning {total_files} batch files in {dataset_dir}...")
    counts = []
    obs_ref_max = None
    img_shape = None
    bad_files = set()

    for i, f in enumerate(files):
        try:
            data = np.load(f)
            imgs = data["images"]
            counts.append(imgs.shape[0])
            if img_shape is None:
                img_shape = imgs.shape[1:]
            if obs_ref_max is None:
                obs_ref_max = float(data["obs_ref_max"])
            data.close()
        except Exception:
            counts.append(0)
            bad_files.add(f)

    if bad_files:
        print(f"  Skipping {len(bad_files)} corrupted files")
        files = [f for f in files if f not in bad_files]
        counts = [c for c in counts if c > 0]

    total_samples = sum(counts)
    mem_gb = total_samples * np.prod(img_shape) * 4 / 1e9
    print(f"  {total_samples:,} images {img_shape}, ~{mem_gb:.1f}GB in {time.time() - t0:.1f}s")

    # --- Pass 2: pre-allocate tensor and fill in-place ---
    print(f"Loading into tensor...")
    t1 = time.time()
    tensor = torch.empty(total_samples, *img_shape, dtype=torch.float32)
    offset = 0

    for i, f in enumerate(files):
        data = np.load(f)
        imgs = data["images"]
        n = imgs.shape[0]
        tensor[offset:offset + n] = torch.from_numpy(imgs).float()
        offset += n
        data.close()

        done = i + 1
        elapsed = time.time() - t1
        eta = elapsed / done * (len(files) - done)
        print(f"\r  [{done}/{len(files)}] "
              f"{elapsed:.1f}s elapsed, ETA {eta:.1f}s", end="", flush=True)

    print()
    print(f"  Ready: {total_samples:,} images in {time.time() - t0:.1f}s, "
          f"obs_ref_max={obs_ref_max:.1f}")
    return tensor, obs_ref_max


# ============================================================================
# Main training loop
# ============================================================================

def train_autoencoder(args):
    if torch.backends.mps.is_available():
        device = torch.device("mps")
    elif torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")
    print(f"Device: {device}")
    print(f"Channel scale: {args.channel_scale}, FC scale: {args.fc_scale}")

    # --- Load dataset ---
    images, obs_ref_max = load_dataset(
        args.dataset_dir, max_files=args.max_files)
    obs_shape = images[0].shape

    # --- Output directory ---
    run_dir = os.path.join(_REPO_ROOT, "runs")
    Path(run_dir).mkdir(parents=True, exist_ok=True)
    run_name = f"autoencoder_{args.seed}_{int(time.time())}"
    this_run_dir = os.path.join(run_dir, run_name)
    os.makedirs(this_run_dir, exist_ok=True)
    log_dir = os.path.join(this_run_dir, "tensorboard")
    writer = SummaryWriter(log_dir)
    print(f"Output: {this_run_dir}")
    print(f"TensorBoard: {log_dir}")

    # --- Build autoencoder ---
    model = OptomechAutoencoder(
        obs_shape=obs_shape,
        channel_scale=args.channel_scale,
        fc_scale=args.fc_scale,
    ).to(device)

    num_params = sum(p.numel() for p in model.parameters())
    print(f"Autoencoder params: {num_params:,}")

    optimizer = optim.Adam(model.parameters(), lr=args.learning_rate)

    # --- Shuffle and split into train / val ---
    channels_last = obs_shape[-1] < obs_shape[0]
    pin = (device.type == "cuda")

    n = len(images)
    perm = torch.randperm(n)
    images = images[perm]

    val_frac = args.val_frac
    n_val = max(1, int(n * val_frac))
    n_train = n - n_val

    train_loader = DataLoader(
        TensorDataset(images[:n_train]),
        batch_size=args.batch_size, shuffle=True,
        drop_last=True, num_workers=0, pin_memory=pin)
    val_loader = DataLoader(
        TensorDataset(images[n_train:]),
        batch_size=args.batch_size, shuffle=False,
        drop_last=False, num_workers=0, pin_memory=pin)

    print(f"Train: {n_train:,}  Val: {n_val:,}  ({val_frac:.0%} held out)")
    print(f"Epochs: {args.num_epochs}, batch size: {args.batch_size}")
    print(f"Batches/epoch: {len(train_loader)} train, {len(val_loader)} val")

    writer.add_scalar("autoencoder/dataset_size", n, 0)
    writer.add_scalar("autoencoder/train_size", n_train, 0)
    writer.add_scalar("autoencoder/val_size", n_val, 0)

    # --- Training ---
    best_val_loss = float("inf")
    global_step = 0
    best_path = os.path.join(this_run_dir, "best.pt")

    num_train_batches = len(train_loader)
    for epoch in range(1, args.num_epochs + 1):
        # -- Train --
        model.train()
        t0 = time.time()
        epoch_losses = []

        for batch_idx, (mb,) in enumerate(train_loader, 1):
            mb = mb.to(device)

            recon = model(mb)
            target = mb.permute(0, 3, 1, 2) if channels_last else mb
            loss = nn.functional.mse_loss(recon, target)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            if batch_idx == 1 or batch_idx % 100 == 0 or batch_idx == num_train_batches:
                elapsed = time.time() - t0
                eta = elapsed / batch_idx * (num_train_batches - batch_idx)
                print(f"\r  Epoch {epoch}/{args.num_epochs} "
                      f"[{batch_idx}/{num_train_batches}] "
                      f"loss={loss.item():.6f} "
                      f"{elapsed:.0f}s/ETA {eta:.0f}s", end="", flush=True)

            epoch_losses.append(loss.item())
            global_step += 1
            writer.add_scalar("autoencoder/step_loss", loss.item(), global_step)

        # -- Validate --
        model.eval()
        val_losses = []
        with torch.no_grad():
            for (mb,) in val_loader:
                mb = mb.to(device)
                recon = model(mb)
                target = mb.permute(0, 3, 1, 2) if channels_last else mb
                val_losses.append(nn.functional.mse_loss(recon, target).item())

        print()  # newline after batch progress
        train_loss = np.mean(epoch_losses)
        val_loss = np.mean(val_losses)
        elapsed = time.time() - t0

        writer.add_scalar("autoencoder/train_loss", train_loss, epoch)
        writer.add_scalar("autoencoder/val_loss", val_loss, epoch)
        writer.add_scalar("autoencoder/best_val_loss",
                          min(best_val_loss, val_loss), epoch)
        writer.add_scalar("autoencoder/learning_rate",
                          optimizer.param_groups[0]["lr"], epoch)

        if epoch % args.log_interval == 0 or epoch == 1:
            print(f"  Epoch {epoch}/{args.num_epochs}  "
                  f"train={train_loss:.6f}  val={val_loss:.6f}  "
                  f"best_val={min(best_val_loss, val_loss):.6f}  "
                  f"time={elapsed:.1f}s")

        # Save best (keyed on validation loss)
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            ckpt = {
                "encoder_state_dict": model.encoder.state_dict(),
                "bottleneck_encode_state_dict":
                    model.bottleneck_encode.state_dict(),
                "full_model_state_dict": model.state_dict(),
                "config": {
                    "channel_scale": int(args.channel_scale),
                    "fc_scale": int(args.fc_scale),
                    "input_channels": int(model.in_ch),
                    "obs_shape": tuple(int(x) for x in obs_shape),
                },
                "val_loss": float(best_val_loss),
                "train_loss": float(train_loss),
                "epoch": int(epoch),
                "global_step": int(global_step),
            }
            torch.save(ckpt, best_path)

    writer.close()
    print(f"\nDone. Best val loss: {best_val_loss:.6f}")
    print(f"Checkpoint: {best_path}")
    print(f"\nTensorBoard: tensorboard --logdir {log_dir}")
    print(f"\nTo use in PPO training:")
    print(f"  python train/ppo/train_ppo_nanoelf_tt.py --env-version v3 "
          f"--pretrained-encoder {best_path}")
    return best_path


# ============================================================================
# CLI
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Train autoencoder on pre-generated dataset")
    parser.add_argument("--fast", action="store_true", help="Smoke test")
    parser.add_argument("--dataset-dir", type=str, default=_DEFAULT_DATASET_DIR,
                        help="Path to dataset folder with batch_*.npz files")
    parser.add_argument("--max-files", type=int, default=None,
                        help="Limit number of batch files to load")
    parser.add_argument("--channel-scale", type=int, default=32)
    parser.add_argument("--fc-scale", type=int, default=256)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--learning-rate", type=float, default=1e-3)
    parser.add_argument("--num-epochs", type=int, default=None)
    parser.add_argument("--batch-size", type=int, default=None)
    parser.add_argument("--log-interval", type=int, default=None)
    parser.add_argument("--val-frac", type=float, default=0.1,
                        help="Fraction of data held out for validation (default: 0.1)")

    args = parser.parse_args()

    if args.fast:
        args.num_epochs = args.num_epochs or 3
        args.batch_size = args.batch_size or 16
        args.log_interval = args.log_interval or 1
        args.max_files = args.max_files or 3
    else:
        args.num_epochs = args.num_epochs or 100
        args.batch_size = args.batch_size or 64
        args.log_interval = args.log_interval or 5

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    train_autoencoder(args)


if __name__ == "__main__":
    main()
